version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: backend-app
    ports:
      - "${BACKEND_PORT}:8000"
    env_file:
      - backend/.env
    depends_on:
      - db
    volumes:
      - ./backend:/code
    
  db:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    env_file:
      - backend/.env
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
